trigger:
  - main

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: 'Build the project'
        steps:
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'MicrosoftHosted'

          - script: |
              ./gradlew.bat build
            displayName: 'Build with Gradle'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'build/libs/*.jar'
              artifactName: 'kotlin-app'
