trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
  - checkout: self
    clean: true

  - task: UseJava@1
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
  
  - script: ./gradlew.bat build
    displayName: 'Build with Gradle'

  - task: CopyFiles@2
    inputs:
      contents: 'build/libs/*.jar'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy Built JAR'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
    displayName: 'Publish Artifact'
