trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  JAVA_HOME: '$(JAVA_HOME_17_X64)'

stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: 'Build the project'
        steps:
          - task: JavaToolInstaller@0
            inputs:
              jdkVersionOption: '1.17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'MicrosoftHosted'
              cleanDestinationDirectory: true

          - script: |
              ./gradlew.bat build
            displayName: 'Build with Gradle'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'build/libs/*.jar'
              artifactName: 'kotlin-app'