trigger:
  - main

pool:
  vmImage: 'windows-latest'

jobs:
- job: BuildAndTest
  steps:
    - task: JavaToolInstaller@0
      inputs:
        jdkSourceOption: 'MicrosoftHosted'
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
    - script: |
        ./gradlew build
      displayName: 'Build with Gradle'
    - task: CopyFiles@2
      inputs:
        contents: 'build/libs/*.jar'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy Built JAR'
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
      displayName: 'Publish Artifact'
