trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
  
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      options: 'build'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'

  - task: CopyFiles@2
    inputs:
      contents: 'build/libs/*.jar'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy Built JAR'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
    displayName: 'Publish Artifact'
