trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'

  - script: |
      ./gradlew build
    displayName: 'Build with Gradle'

  - task: CopyFiles@2
    inputs:
      contents: 'build/libs/*.jar'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy Built JAR'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
    displayName: 'Publish Artifact'
